---
version: '3'
volumes:
  kali-persist:
services:
  kali:
    build: .
    image: nucleardreamer/kali-crackbase
    network_mode: host
    privileged: true
    tty: true
    volumes:
      - /mnt:/mnt:ro
      - /dev:/dev
      - kali-persist:/persist:rw
      - ./output:/output
    ports:
      - 9999:9999
    # command: mkimg /dev/sda mybackup.dd
